---

- name: Ensure default Centos deps are available.
  yum:
    name: 
      - firewalld
      - which
    state: present
  notify: restart dbus

- name: Ensure httpd service is stopped and disabled for pacemaker
  systemd:
    name: httpd
    state: stopped
    enabled: false

- name: Add each node to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: Add Apache status config to each node
  copy:
    src: httpd/conf.d/status.conf
    dest: /etc/httpd/conf.d/status.conf
    owner: root
    group: root
    mode: '0644'

- name: Install pacemaker
  yum:
    name:
      - pacemaker
      - pcs
    state: present

- name: Start and enable pcsd
  systemd:
    name: pcsd
    state: started
    daemon_reload: yes
    enabled: true 

- name: Start and enable firewalld    
  systemd:
    name: firewalld
    state: started
    daemon_reload: yes   
    enabled: true

- name: Set common password for hacluster user
  user:
    name: hacluster
    password: "{{ hacluster_password }}"

- name: Add high-availability service to firewalld
  firewalld:
    service: high-availability
    permanent: true
    state: enabled
  notify: reload firewalld

- name: Add http service to firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify: reload firewalld

- name: Add https service to firewalld
  firewalld:
    service: https
    permanent: true
    state: enabled
  notify: reload firewalld

- name: ensure Corosync is enabled
  systemd:
    name: corosync
    daemon_reload: yes
    enabled: true

- name: ensure Pacemaker is enabled
  systemd:
    name: pacemaker
    daemon_reload: yes
    enabled: true
